# app/config — настройки приложения + игровые балансы.
#
# app/config.py был преобразован в пакет app/config/
# Все `from app.config import settings` продолжают работать через реэкспорт.

# ── Pydantic-settings (бывший app/config.py) ─────────────────────────────────
from app.config.settings import Settings, settings  # noqa: F401

# ── Игровой баланс ────────────────────────────────────────────────────────────
from app.config.game_balance import (
    REFERRAL_TEACHER_BONUS_COINS,
    REFERRAL_STUDENT_POWER_BONUS,
    DEFAULT_MAX_TICKETS,
    DEFAULT_TICKET_CHANCE,
    DEFAULT_INFLUENCE,
    TUI_MAX_TICKETS,
    EXTRA_SKILL_SLOTS_BASE,
    EXTRA_SKILL_SLOTS_WITH_TITLE,
    KING_BOT_WIN_INFLUENCE,
    KING_BOT_WIN_COINS_CAP,
    KING_BOT_WIN_COINS_DIVISOR,
    CLAN_WAR_WINNER_MULTIPLIER,
    CLAN_WAR_LOSER_MULTIPLIER,
    CLAN_WAR_WINNER_BASE,
    CLAN_WAR_LOSER_BASE,
    CLAN_WAR_MAX_REWARD,
    CLAN_WAR_POWER_HOURS,
    CLAN_WAR_TREASURY_HOURS,
    CITIES_NEEDED_FOR_KING,
    FIST_WINS_NEEDED,
)

from app.config.rate_limit import (
    RATE_LIMIT_REQUESTS,
    RATE_LIMIT_WINDOW,
    RATE_LIMIT_MAX_VIOLATIONS,
    RATE_LIMIT_BAN_SECONDS,
)

from app.config.scheduler_config import (
    INCOME_TICK_MINUTES,
    UI_TICK_MINUTES,
    AUCTION_ROUND_TICK_SECONDS,
    AUCTION_START_TICK_MINUTES,
    REFERRAL_POWER_TICK_MINUTES,
    CLAN_WAR_TICK_MINUTES,
    CLAN_AUCTION_TICK_MINUTES,
)

__all__ = [
    "Settings",
    "settings",
    "REFERRAL_TEACHER_BONUS_COINS",
    "REFERRAL_STUDENT_POWER_BONUS",
    "DEFAULT_MAX_TICKETS",
    "DEFAULT_TICKET_CHANCE",
    "DEFAULT_INFLUENCE",
    "TUI_MAX_TICKETS",
    "EXTRA_SKILL_SLOTS_BASE",
    "EXTRA_SKILL_SLOTS_WITH_TITLE",
    "KING_BOT_WIN_INFLUENCE",
    "KING_BOT_WIN_COINS_CAP",
    "KING_BOT_WIN_COINS_DIVISOR",
    "CLAN_WAR_WINNER_MULTIPLIER",
    "CLAN_WAR_LOSER_MULTIPLIER",
    "CLAN_WAR_WINNER_BASE",
    "CLAN_WAR_LOSER_BASE",
    "CLAN_WAR_MAX_REWARD",
    "CLAN_WAR_POWER_HOURS",
    "CLAN_WAR_TREASURY_HOURS",
    "CITIES_NEEDED_FOR_KING",
    "FIST_WINS_NEEDED",
    "RATE_LIMIT_REQUESTS",
    "RATE_LIMIT_WINDOW",
    "RATE_LIMIT_MAX_VIOLATIONS",
    "RATE_LIMIT_BAN_SECONDS",
    "INCOME_TICK_MINUTES",
    "UI_TICK_MINUTES",
    "AUCTION_ROUND_TICK_SECONDS",
    "AUCTION_START_TICK_MINUTES",
    "REFERRAL_POWER_TICK_MINUTES",
    "CLAN_WAR_TICK_MINUTES",
    "CLAN_AUCTION_TICK_MINUTES",
]
